spring:

  datasource:
    url: jdbc:postgresql://user-db:5432/user-db
    username: userdatabaseuser
    password: superuberman

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          charSet: UTF-8

server:
  port: 8081
