spring:

  datasource:
    url: jdbc:postgresql://board-db:5432/board-db
    username: postgres
    password: superuberman

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          charSet: UTF-8
