spring:
  datasource:
    url: jdbc:postgresql://board-db:5432/board-db
    username: board-db-user
    password: board-db-password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

user-service-http:
  url: http://user-service:8081/api/v1/users/

server:
  port: 8080
